### ISSUE TITLE
join on strings fails

### ISSUE THREAD

**Issue by nw11** [davidanthoff/Query.jl#116] opened 2017-05-27 16:44 UTC
The documentation for join has this example:
```
df1 = DataFrame(a=[1,2,3], b=[1.,2.,3.])
df2 = DataFrame(c=[2,4,2], d=["John", "Jim","Sally"])
```
Then
``` 
x = @from i in df1 begin
    @join j in df2 on i.a equals j.c
    @select {i.a,i.b,j.d}
    @collect DataFrame
end
```
gives a 2x3 DataFrame.

But if the joining fields are changed to hold strings 
```
df1 = DataFrame(a=["1","2","3"], b=[1.,2.,3.])
df2 = DataFrame(c=["2","4","2"], d=["John", "Jim","Sally"])
```
then you end up with a 0x3 DataFrame instead after the join query above.

Using 0.4.0 tagged Query.jl on Julia 0.5.2-pre+1 This looks like it has something to do with the switch to using DataValues?

**Comment by davidanthoff** [comment] 2017-05-28 04:51
Thanks for reporting this! The root cause was a silly bug in my ``DataValue`` implementation. Query.jl v0.4.1 should have that fixed, just waiting for that version to show up in the official package repo (JuliaLang/METADATA.jl#9563).

I'm closing the issue for now, but please let me know if this fix doesn't work for you and then I would reopen it.

**Closed by davidanthoff** 2017-05-28 04:51 UTC

**Comment by nw11** [comment] 2017-05-31 10:50
thanks David! works for me now.
