### ISSUE TITLE
Documentation request: how to get an SQL style outer join

### ISSUE THREAD

**Issue by tcovert** [davidanthoff/Query.jl#57] opened 2016-09-27 04:30 UTC
Would it be possible to explain how to implement SQL-style outer joins in Query.jl?  That is, joins whose resulting collected output have columns with scalar element types instead of arrays.  I'm guessing this is possible, but I was not able to figure it out based on either the existing documentation or basic google searches for "full outer join linq".

**Comment by davidanthoff** [comment] 2016-09-27 05:15
See [here](https://msdn.microsoft.com/en-us/library/bb397895.aspx?f=255&MSPPError=-2147217396). But that is really cumbersome, so it would probably make sense to add another dedicated statement for this quite common case (see #39).

Totally agreed that this should be described in the Query.jl documentation itself, I've added it to the backlog. PRs on the documentation are also welcome! I believe this would fit in well under the "Query Command" -> "Joining" section.

**Comment by tcovert** [comment] 2016-09-27 13:42
Thanks for the suggestion.  Based on that link, I would think that something like this ought to work:
```
using DataFrames, Query, NamedTuples

df1 = DataFrame(a=[1,2,3], b=[1.,2.,3.])
df2 = DataFrame(c=[2,4,2], d=["John", "Jim","Sally"])

@from i in df1 begin
       @join j in df2 on i.a equals j.c into k
       @from kk in k
       @select {i.a, kk}
       @collect DataFrame
end
```

but upon execution, I get a really long error report, starting with:
```
ERROR: UndefVarError: i not defined
 in (::FunctionWrappers.CallWrapper{NamedTuples._NT_akk})(::##251#256, ::NamedTuples._NT_ik{NamedTuples._NT_ab{Nullable{Int64},Nullable{Float64}},Array{NamedTuples._NT_cd{Nullable{Int64},Nullable{String}},1}}, ::NamedTuples._NT_cd{Nullable{Int64},Nullable{String}}) at ./<missing>:0
```

**Comment by davidanthoff** [comment] 2016-09-27 17:09
That is a bug. I just figured out what the problem is and will try to fix soon. Thanks for finding this one! I'm tracking the bug in #58, and will leave this issue for tracking the required doc update.

**Comment by davidanthoff** [comment] 2016-09-27 17:27
The bug should be fixed. But I think we might also not have the equivalent of the C# ``DefaultIfEmpty`` method, which we need for this to work... Tracking that in #59.

**Comment by davidanthoff** [comment] 2016-09-28 00:44
I've just pushed some commits that add a ``@left_outer_join`` statement, so this should be way easier going forward.

**Closed by davidanthoff** 2016-09-28 00:44 UTC
Labels: enhancement
